### ISSUE TITLE
Tag first release

### ISSUE THREAD

**Issue by jawshooah** [jasonkarns/node-build-update-defs#8]
Want to tag a release so I can move this from `homebrew-nodenv-head-only` to `homebrew-nodenv`?

**Comment by jasonkarns** [comment]
tagged https://github.com/jasonkarns/node-build-update-defs/releases/tag/v1.0.0

**Comment by jawshooah** [comment]
Added in jawshooah/homebrew-nodenv@d8283d03832652dc41f981de3bc4e0ce0ab86242
